version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    depends_on:
      - app
    volumes:
      - ./backend:/work/backend
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./backend:/work/backend
